
version: "3.9"

services:
  prontmed-frontend:
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}
      - REACT_APP_BASE_URL_TODOS=${REACT_APP_BASE_URL}/todos
    ports:
      - 3000:3000
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8082:8080"
    volumes:
      - ./test-backend.yaml:/prontmed-backend.yaml
    environment:
      SWAGGER_JSON: /prontmed-backend.yaml
      # API_URL: ""
